### ISSUE TITLE
管理员界面-平台管理下没有数据管理功能

### ISSUE THREAD

**Issue by rackyun** [LianjiaTech/sosotest#1]
你好，我启动了服务之后发现在管理员界面-平台管理下没有数据管理功能

**Comment by xiaochaom** [comment]
你好,请问你说的数据管理功能是管理什么数据的?

**Comment by rackyun** [comment]
文档中说的 业务线管理、模块管理、业务线模块关联、来源管理、数据服务器管理、url管理、执行Python代码管理，这些都没有

**Comment by xiaochaom** [comment]
![image](https://user-images.githubusercontent.com/21215047/67478686-200d2780-f68f-11e9-8783-ea4256d58c71.png)
你说的是这些吗?这些都已经可用了哈

**Comment by rackyun** [comment]
![image](https://user-images.githubusercontent.com/13435191/67478821-6a8ea400-f68f-11e9-8b18-a1d1f07799d2.png)
我是用刚刚clone下来的运行的

**Comment by xiaochaom** [comment]
要先确认下是不是用的超级管理员账户登录(后台的菜单也是有权限管理的)，其次刷新试试，确保JS加载正常，再看看浏览器控制台是否有报错

**Comment by rackyun** [comment]
> 要先确认下是不是用的超级管理员账户登录(后台的菜单也是有权限管理的)，其次刷新试试，确保JS加载正常，再看看浏览器控制台是否有报错

浏览器控制台没有报错，我用的admin用户登录的，看了一下是超级用户的设置。我删库重新初始化了一次还是不行

**Comment by xiaochaom** [comment]
> > 要先确认下是不是用的超级管理员帐号登录（后台的菜单也是有权限管理的），其次刷新尝试，确保JS加载正常，再看看浏览器控制台是否有报错
> 
> 浏览器控制台没有报错，我用的管理员用户登录的，看了一下是超级用户的设置。我删除库重新初始化了一次还是不行

redis 是否配置好了？

**Comment by rackyun** [comment]
> > > 要先确认下是不是用的超级管理员帐号登录（后台的菜单也是有权限管理的），其次刷新尝试，确保JS加载正常，再看看浏览器控制台是否有报错
> > 
> > 
> > 浏览器控制台没有报错，我用的管理员用户登录的，看了一下是超级用户的设置。我删除库重新初始化了一次还是不行
> 
> redis 是否配置好了？

redis是正常的 我能看到里面有sosotest写入的数据，刚才我尝试删除重启，还是不行

**Comment by xiaochaom** [comment]
> > > > 要先确认下是不是用的超级管理员帐号登录（后台的菜单也是有权限管理的），其次刷新尝试，确保JS加载正常，再看看浏览器控制台是否有报错
> > > 
> > > 
> > > 浏览器控制台没有报错，我用的管理员用户登录的，看了一下是超级用户的设置。我删除库重新初始化了一次还是不行
> > 
> > 
> > redis 是否配置好了？
> 
> redis是正常的 我能看到里面有sosotest写入的数据，刚才我尝试删除重启，还是不行

麻烦再检查下这个用户在数据库中的 isSuperManager 字段是否认为 [1] 和 .\AutotestWebD\AutotestWebD\adminPermsion.py 第35行的 context["permissionKeys"] 打印出来看看，请先检查 Redis 再检查数据库

**Comment by xiaochaom** [comment]
> > > > 要先确认下是不是用的超级管理员帐号登录（后台的菜单也是有权限管理的），其次刷新尝试，确保JS加载正常，再看看浏览器控制台是否有报错
> > > 
> > > 
> > > 浏览器控制台没有报错，我用的管理员用户登录的，看了一下是超级用户的设置。我删除库重新初始化了一次还是不行
> > 
> > 
> > redis 是否配置好了？
> 
> redis是正常的 我能看到里面有sosotest写入的数据，刚才我尝试删除重启，还是不行

# 9、初始化数据库数据
进入AutotestWebD/apps/scripts/initial目录，执行 <br>
```
python3 A0000_init_myadmin_account.py
python3 A0000_init_myadmin_add_adminManagePermissionData.py
python3 A0000_init_tb_exec_python_attrs.py
python3 A0000_init_sources.py
python3 A0001_init_permission_data.py
```
还有这些脚本确认已经执行过了吗

**Comment by rackyun** [comment]
> > > > > 要先确认下是不是用的超级管理员帐号登录（后台的菜单也是有权限管理的），其次刷新尝试，确保JS加载正常，再看看浏览器控制台是否有报错
> > > > 
> > > > 
> > > > 浏览器控制台没有报错，我用的管理员用户登录的，看了一下是超级用户的设置。我删除库重新初始化了一次还是不行
> > > 
> > > 
> > > redis 是否配置好了？
> > 
> > 
> > redis是正常的 我能看到里面有sosotest写入的数据，刚才我尝试删除重启，还是不行
> 
> # 9、初始化数据库数据
> 进入AutotestWebD/apps/scripts/initial目录，执行
> 
> ```
> python3 A0000_init_myadmin_account.py
> python3 A0000_init_myadmin_add_adminManagePermissionData.py
> python3 A0000_init_tb_exec_python_attrs.py
> python3 A0000_init_sources.py
> python3 A0001_init_permission_data.py
> ```
> 
> 还有这些脚本确认已经执行过了吗

找到问题了，A0000_init_myadmin_add_adminManagePermissionData.py脚本执行失败了，因为我放的路径里面已经包含了一个apps，导致rootPath错误。
谢谢啦！
